### ISSUE TITLE
Prefix items

### ISSUE THREAD

**Issue by surgura** [eqrion/cbindgen#168]
In the documentation it is listed that you can prefix all items using the config
``` toml
[export]
prefix = "onec_"
```

However, this does not seem to work (for me). All options work, except for this one. My function
``` rust
#[no_mangle]
pub extern "C" fn foo()
{
    return;
}
```
is still output as:
``` c
void foo(void);
```

My `cbindgen.toml`:
``` toml
include_guard = "ONEC_CORE_H"
braces = "NextLine"
tab_width = 4
language = "C"

[export]
prefix = "onec_"

[fn]
rename_args = "SnakeCase"

[struct]
rename_fields = "SnakeCase"

[enum]
rename_variants = "SnakeCase"
```
