### ISSUE TITLE
support cfg_attr with repr() and no_mangle

### ISSUE THREAD

**Issue by fzzr-** [eqrion/cbindgen#183]
```rust
#[cfg_attr(feature = "cffi", repr(C))]
#[cfg_attr(feature = "cffi", no_mangle)]
pub struct Token { foo: u8 }
```

cbindgen.toml:
```toml
language = "C"

[export]
include = [ "Token" ]

[parse]
parse_deps = false

[defines]
feature = "cffi"
```

`> cbindgen -v -c ./cbindgen.toml -o ./include.h`

So cbindgen sayd "INFO: Take gog-api::Token - opaque (Struct is not marked #[repr(C)].)." and the output include.h is empty.

**Comment by regexident** [comment]
Recognizing every possible attribute is kind of a lost cause, due to procedural attribute macros.

Case in point: https://github.com/regexident/apply_attr

Fortunately for those things there is cbindgen's `expand` feature for the rescue …

```toml
[parse]
expand = ["crate-name"]
```

… which will properly resolve your example, even without your PR https://github.com/eqrion/cbindgen/pull/189.

Using `[parse.expand]` for all crates by default would solve this whole bag of issues, I think.
What would be the down-side of expand by default, @eqrion? Performance, I guess?
