### ISSUE TITLE
Forward declaration of all pointers

### ISSUE THREAD

**Issue by Kamayuq** [eqrion/cbindgen#215]
cbindgen does not forward declare its pointers or struct members when they are used in the generated header.  One could even inline forward declare following rust types for each place they are used as pointers: "struct Name();" The reason why I am asking for this is that I want to split my interface into multiple modules, headers and c/cpp files. And as of now I have to forward declare certain pointer-types that are shared between the modules.

**Comment by eqrion** [comment]
Could you elaborate more on what you'd like `cbindgen` to do? An example would help.

**Comment by eqrion** [comment]
This sounds like cbindgen isn't parsing the somecrate to find type definitions. If it were it would generate forward declarations for you.

See the parse section of Config:
```toml
[parse]
# Whether to parse dependent crates and include their types in the generated
# bindings
parse_deps = true
# A white list of crate names that are allowed to be parsed
include = ["webrender", "webrender_traits"]
# A black list of crate names that are not allowed to be parsed
exclude = ["libc"]
```

**Comment by Kamayuq** [comment]
I set parse_deps to true. Although I did not whitelist or blacklist anything as my use case programmatically adds rs files to create the binding for and I did not want to parse the rs file just to figure out what to whitelist.

**Comment by DoumanAsh** [comment]
It would be nice to have option to typedef unknown structs as `void` so that you could still use them as pointers to Rust structs, but expose it to C as `void`

**Comment by Wodann** [comment]
@eqrion I have a use case where I need to use a pointer to a `struct` that has not been defined yet. It seems that `cbindgen` does forward declare the `struct` (with my current settings), resulting in a `error C4430: missing type specifier - int assumed. Note: C++ does not support default-int`. This is a minimal reproduction of my use case:

```c
typedef struct {
    // Other data goes here...
    const MunTypeInfo *const *field_types; // To solve the issue, this should be `const struct MunTypeInfo*`
    uint16_t num_fields;
} MunStructInfo;

enum MunTypeInfoData_Tag
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    Primitive,
    Struct,
};
#ifndef __cplusplus
typedef uint8_t MunTypeInfoData_Tag;
#endif // __cplusplus

typedef struct {
    MunTypeInfoData_Tag tag;
    MunStructInfo _0;
} MunStruct_Body;

typedef union {
    MunTypeInfoData_Tag tag;
    MunStruct_Body struct_;
} MunTypeInfoData;

typedef struct { // To solve the issue, this should be `typedef struct MunTypeInfo`
    // Other data goes here ...
    MunTypeInfoData data;
} MunTypeInfo;
```

The corresponding `cbindgen.toml` is:
```toml
language = "C"
cpp_compat = true

include_guard = "MUN_RUNTIME_BINDINGS_H_"
include_version = true
sys_includes = ["stdbool.h", "stdint.h"]
no_includes = true

line_length = 100
tab_width = 4

[export]
prefix = "Mun"

[parse]
parse_deps = true
include = ["mun_abi", "mun_memory", "mun_runtime"]
```

If you have any pointers on how I can solve this, please let me know. Otherwise I'll dive into the `cbindgen` code myself 🙂
