### ISSUE TITLE
cbindgen 0.6.4 moved constants outside namespace

### ISSUE THREAD

**Issue by staktrace** [eqrion/cbindgen#229]
The constants at https://searchfox.org/mozilla-central/rev/9cb3e241502a2d47e2d5057ca771324a446b6695/gfx/webrender_bindings/webrender_ffi_generated.h#20,22 are inside the mozilla::wr namespace. With cbindgen 0.6.4 they get moved outside the namespace which is undesirable.

**Comment by staktrace** [comment]
Actually these constants are generated from https://searchfox.org/mozilla-central/rev/9cb3e241502a2d47e2d5057ca771324a446b6695/gfx/webrender_bindings/src/program_cache.rs#16 and are never used on the C++ side so if there's a way to omit them from being generated that would be fine too.

**Comment by staktrace** [comment]
This appears to be a result of the changes in #170 to bindings.rs, it explicitly moved the namespace opening down to after the constants were written. @IGI-111 was this intentional? None of the tests added seem to have namespaces so I'm wondering if this change was accidental.

**Comment by staktrace** [comment]
I guess it was intentional, because only constants of type `is_primitive_or_ptr_primitive()` got moved outside the namespace. But I'm not sure why.

**Comment by eqrion** [comment]
I don't recall the reason why constants of type `is_primitive_or_ptr_primitive()` were moved outside namespaces. I know `!is_primitive_or_ptr_primitive()` were moved to be after all items were output so they have the right definitions.

**Comment by eqrion** [comment]
@staktrace As a stopgap you could skip emitting constants.

```toml
[export]
# don't have a negative version of item-types unfortunately
# item-types = ["Constants", "Globals", "Enums", "Structs", "Unions", "Typedefs", "OpaqueItems", "Functions"]
item-types = ["Globals", "Enums", "Structs", "Unions", "Typedefs", "OpaqueItems", "Functions"]
```
