### ISSUE TITLE
rename_variants should honor export.rename 

### ISSUE THREAD

**Issue by ralfbiedert** [eqrion/cbindgen#366]
## Current Behavior 

We have a: 

```toml
[export.rename]
"Result" = "g2om_result"
```

which produces:

```c
typedef enum {
  Ok = 0,
} g2om_result;
```

If I now also specify 

```toml
[enum]
rename_variants = "QualifiedScreamingSnakeCase"
```

My enums look like this

```c
typedef enum {
  RESULT_OK = 0,
} g2om_result;
```

## Expected Behavior

Instead, I would expect `QualifiedScreamingSnakeCase` to honor my renames, so that instead this enum is produced:

```c
typedef enum {
   G2OM_RESULT_OK = 0,
} g2om_result;
```
## Tested on

cbindgen version: `0.9`
