### ISSUE TITLE
Macro expansion breaks dependency inclusion

### ISSUE THREAD

**Issue by vmx** [eqrion/cbindgen#384]
There is a bug when using dependencies and macro expansion on the crate that cbindgen is run on.

This bug exposes the same issue as described at https://github.com/eqrion/cbindgen/issues/292,  but only if

```toml
[parse.expand]
crates = ["cbindgen-dep"]
```

is used in cbindgen.toml.
