### ISSUE TITLE
cpp_compat option ignores namespace

### ISSUE THREAD

**Issue by adamski** [eqrion/cbindgen#391]
The following config

```toml
language = "C"
cpp_compat = true
include_version = false
namespace = "acme"
```

Results in no namespace being included in the generated header within the ` #ifdef __cplusplus ` sections. 

I would expect something like this to be generated:

```cpp
#ifdef __cplusplus
namespace acme {
extern "C" {
#endif // __cplusplus

void print_hello(void);

#ifdef __cplusplus
} // extern "C"
} // namespace acme
#endif // __cplusplus
```
