### ISSUE TITLE
Panics with parse_deps=true

### ISSUE THREAD

**Issue by RazrFalcon** [eqrion/cbindgen#493]
When running cbindgen in [this](https://github.com/RazrFalcon/ttf-parser/tree/master/c-api) dir with such config:

```toml
language = "C"
include_guard = "TTFP_H"
braces = "SameLine"
tab_width = 4
documentation_style = "doxy"

[defines]
"feature = logging" = "ENABLE_LOGGING"

[fn]
sort_by = "None"

[parse]
parse_deps = true
```
 I'm getting:

`thread 'main' panicked at 'called Option::unwrap() on a None value', /home/razr/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.13.1/src/bindgen/parser.rs:687:25`
