### ISSUE TITLE
`struct` keyword omitted in C bindings

### ISSUE THREAD

**Issue by dfarley1** [eqrion/cbindgen#621]
I'm using bindgen and cbindgen together to build both C->Rust and Rust->C headers so we can start writing pieces of our C code in Rust. I think the issue boils down to the fact that our codebase does not use `typedef` or any other kinds of aliasing to mask the `struct` keyword in usage.

I have a `struct foo` declared in C that I'd like to use in Rust functions.
```C
struct foo {
    int bar;
};
```

Using bindgen I get the following bits in `bindings.rs`
```Rust
...
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct flow {
    pub bar: u32
}
...
```

and I have some Rust functions which take `struct flow *` arguments as `*mut flow`
`foo.rs`
```Rust
#[no_mangle]
pub extern "C" fn rust_use_foo(foo: *mut foo) -> bool {
    // ...
}
```

The bits I get from cbindgen are
```C
...
bool rust_use_foo(foo *foo);
...

I've set `style="tag"` in my `cbindgen.toml` but that only seems to affect structs declared by cbindgen and their usage. How can I get cbindgen to use `struct foo*` instead of `foo*` in function parameters even for structs which cbindgen does not know about?

**Comment by RReverser** [comment]
Did you set output language to C? Default is C++: https://github.com/eqrion/cbindgen/blob/51405d1277690e4eb4c615fc9045a8c89bbc125b/template.toml#L9

**Comment by dfarley1** [comment]
Yeah I did, here's my full `cbindgen.toml`
```toml
language = "C"
autogen_warning = "/* This file is autogenerated by cbindgen. Don't modify this manually. */"
cpp_compat = true
braces = "SameLine"
line_length = 80
tab_width = 4
documentation_style = "c"
style = "tag"
```
