### ISSUE TITLE
CI-Runner: command cbindgen not found

### ISSUE THREAD

**Issue by Nevsden** [eqrion/cbindgen#650]
This issue is probably not in particular related to cbindgen, however I did not find a satisfying answer on sides as SO, etc.

I want to set up a gitlab CI using `cbindgen` to automatically generate the header files for me. After the CI pipeline has successfully installed the cbindgen command, the runner tells me, it cannot find the command: `/bin/bash: line 110: cbindgen: command not found` Is there any update mechanism I can use for the current shell to recognize this command? 

This minimal example resembles my yaml script:

```yml
rust_create_header:
    stage: deploy
    only:
        - dev
    image: rust:slim
    before_script:
        - cargo install --force cbindgen
    script:
        - cbindgen --config cbindgen.toml --crate ghost_bindings --output ghost.h
        - cp ghost.h build/ghost.h
    artifacts:
        paths:
            - build/
        expire_in: never
    tags:
        - asprunner
```
