### ISSUE TITLE
Associated constants processed incorrectly

### ISSUE THREAD

**Issue by RazrFalcon** [eqrion/cbindgen#683]
```rust
#[repr(C)]
pub struct Test {
    pub data: [u8; Self::LEN],
}

impl Test {
    pub const LEN: usize = 8;
}
```

```c
typedef struct {
    uint8_t data[LEN];
} Test;
#define Test_LEN 8
```

```toml
language = "C"
cpp_compat = true
style = "type"
```
