### ISSUE TITLE
Not possible to set `bitflags=true` in `build.rs`?

### ISSUE THREAD

**Issue by shayne-fletcher** [eqrion/cbindgen#700]
I'm looking for a way to achieve the equivalent of
```toml
[macro_expansion]
bitflags = true
```
in my `build.rs` but it doesn't appear possible?
