### ISSUE TITLE
export.mangle rename_types = "snake_case" not working

### ISSUE THREAD

**Issue by TomzBench** [eqrion/cbindgen#763]
i have 

```toml
[export.mangle]
rename_types = "snake_case"
```

I have structs such as MyStruct, and i expect the header to rename this type to `my_struct` however it does not seem to be renamed in the header.
